### Create report
POST http://localhost:3000/reports
content-type: application/json

{
  "price": 122000,
  "make": "Mercedes",
  "model": "E200",
  "year": 2010,
  "mileage": 100000,
  "lng": 0,
  "lat": 0
}

### Find report
GET http://localhost:3000/reports/6


### Update report
PATCH http://localhost:3000/reports/6
content-type: application/json

{
  "approved": true
}


### Get Estimate
GET http://localhost:3000/reports?make=Mercedes