### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "crypt@asdf.com",
  "password": "1232311222"
}

### Find a user
GET http://localhost:3000/auth/2

### Find a user by email
GET http://localhost:3000/auth?email=updatedEmail@asdf.com

### Find a user by email
DELETE http://localhost:3000/auth/1

### Update a user by email
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "updatedEmail@asdf.com",
  "password": "newPass111"
}