### Signup
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "",
  "password": ""
}

### Signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "",
  "password": ""
}

### Signout
POST http://localhost:3000/auth/signout
content-type: application/json


### Get current user
GET http://localhost:3000/auth/current_user

### Find a user
GET http://localhost:3000/auth/2

### Find a user by email
GET http://localhost:3000/auth?email=updatedEmail@asdf.com

### Find a user by email
DELETE http://localhost:3000/auth/1

### Update a user by email
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "",
  "password": ""
}